version: "3.5"

services:
  mc:
    image: itzg/minecraft-server

    ports:
      - "25565:25565"

    volumes:
      - "./data/:/data"

    environment:
      EULA: "TRUE"
      VERSION: "1.7.10"
      TYPE: FORGE
      FORGEVERSION: "10.13.4.1614"
      MEMORY: 2G
      MIN_RAM: 2G
      MAX_RAM: 3G
      WHITELIST: mikan_megane
      OPS: mikan_megane

    container_name: mc

    tty: true
    stdin_open: true
    # restart: always
